# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sentenac/ZCM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sentenac/ZCM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sentenac/ZCM/CMakeFiles /home/sentenac/ZCM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sentenac/ZCM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zcm

# Build rule for target.
zcm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm
.PHONY : zcm

# fast build rule for target.
zcm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/build
.PHONY : zcm/fast

#=============================================================================
# Target rules for targets named zcm_smoke

# Build rule for target.
zcm_smoke: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm_smoke
.PHONY : zcm_smoke

# fast build rule for target.
zcm_smoke/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_smoke.dir/build.make CMakeFiles/zcm_smoke.dir/build
.PHONY : zcm_smoke/fast

#=============================================================================
# Target rules for targets named zcm_msg_roundtrip

# Build rule for target.
zcm_msg_roundtrip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm_msg_roundtrip
.PHONY : zcm_msg_roundtrip

# fast build rule for target.
zcm_msg_roundtrip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_roundtrip.dir/build.make CMakeFiles/zcm_msg_roundtrip.dir/build
.PHONY : zcm_msg_roundtrip/fast

#=============================================================================
# Target rules for targets named zcm_msg_fuzz

# Build rule for target.
zcm_msg_fuzz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm_msg_fuzz
.PHONY : zcm_msg_fuzz

# fast build rule for target.
zcm_msg_fuzz/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_fuzz.dir/build.make CMakeFiles/zcm_msg_fuzz.dir/build
.PHONY : zcm_msg_fuzz/fast

#=============================================================================
# Target rules for targets named zcm_msg_vectors

# Build rule for target.
zcm_msg_vectors: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm_msg_vectors
.PHONY : zcm_msg_vectors

# fast build rule for target.
zcm_msg_vectors/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_vectors.dir/build.make CMakeFiles/zcm_msg_vectors.dir/build
.PHONY : zcm_msg_vectors/fast

#=============================================================================
# Target rules for targets named zcm_broker_main

# Build rule for target.
zcm_broker_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm_broker_main
.PHONY : zcm_broker_main

# fast build rule for target.
zcm_broker_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_broker_main.dir/build.make CMakeFiles/zcm_broker_main.dir/build
.PHONY : zcm_broker_main/fast

#=============================================================================
# Target rules for targets named zcm_broker_ctl

# Build rule for target.
zcm_broker_ctl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm_broker_ctl
.PHONY : zcm_broker_ctl

# fast build rule for target.
zcm_broker_ctl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_broker_ctl.dir/build.make CMakeFiles/zcm_broker_ctl.dir/build
.PHONY : zcm_broker_ctl/fast

#=============================================================================
# Target rules for targets named zcm_pub

# Build rule for target.
zcm_pub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm_pub
.PHONY : zcm_pub

# fast build rule for target.
zcm_pub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_pub.dir/build.make CMakeFiles/zcm_pub.dir/build
.PHONY : zcm_pub/fast

#=============================================================================
# Target rules for targets named zcm_sub

# Build rule for target.
zcm_sub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm_sub
.PHONY : zcm_sub

# fast build rule for target.
zcm_sub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_sub.dir/build.make CMakeFiles/zcm_sub.dir/build
.PHONY : zcm_sub/fast

#=============================================================================
# Target rules for targets named zcm_bytes_pub

# Build rule for target.
zcm_bytes_pub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm_bytes_pub
.PHONY : zcm_bytes_pub

# fast build rule for target.
zcm_bytes_pub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_bytes_pub.dir/build.make CMakeFiles/zcm_bytes_pub.dir/build
.PHONY : zcm_bytes_pub/fast

#=============================================================================
# Target rules for targets named zcm_bytes_sub

# Build rule for target.
zcm_bytes_sub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zcm_bytes_sub
.PHONY : zcm_bytes_sub

# fast build rule for target.
zcm_bytes_sub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_bytes_sub.dir/build.make CMakeFiles/zcm_bytes_sub.dir/build
.PHONY : zcm_bytes_sub/fast

#=============================================================================
# Target rules for targets named cm_bridge

# Build rule for target.
cm_bridge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cm_bridge
.PHONY : cm_bridge

# fast build rule for target.
cm_bridge/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm_bridge.dir/build.make CMakeFiles/cm_bridge.dir/build
.PHONY : cm_bridge/fast

examples/zcm_broker_ctl.o: examples/zcm_broker_ctl.c.o
.PHONY : examples/zcm_broker_ctl.o

# target to build an object file
examples/zcm_broker_ctl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_broker_ctl.dir/build.make CMakeFiles/zcm_broker_ctl.dir/examples/zcm_broker_ctl.c.o
.PHONY : examples/zcm_broker_ctl.c.o

examples/zcm_broker_ctl.i: examples/zcm_broker_ctl.c.i
.PHONY : examples/zcm_broker_ctl.i

# target to preprocess a source file
examples/zcm_broker_ctl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_broker_ctl.dir/build.make CMakeFiles/zcm_broker_ctl.dir/examples/zcm_broker_ctl.c.i
.PHONY : examples/zcm_broker_ctl.c.i

examples/zcm_broker_ctl.s: examples/zcm_broker_ctl.c.s
.PHONY : examples/zcm_broker_ctl.s

# target to generate assembly for a file
examples/zcm_broker_ctl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_broker_ctl.dir/build.make CMakeFiles/zcm_broker_ctl.dir/examples/zcm_broker_ctl.c.s
.PHONY : examples/zcm_broker_ctl.c.s

examples/zcm_broker_main.o: examples/zcm_broker_main.c.o
.PHONY : examples/zcm_broker_main.o

# target to build an object file
examples/zcm_broker_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_broker_main.dir/build.make CMakeFiles/zcm_broker_main.dir/examples/zcm_broker_main.c.o
.PHONY : examples/zcm_broker_main.c.o

examples/zcm_broker_main.i: examples/zcm_broker_main.c.i
.PHONY : examples/zcm_broker_main.i

# target to preprocess a source file
examples/zcm_broker_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_broker_main.dir/build.make CMakeFiles/zcm_broker_main.dir/examples/zcm_broker_main.c.i
.PHONY : examples/zcm_broker_main.c.i

examples/zcm_broker_main.s: examples/zcm_broker_main.c.s
.PHONY : examples/zcm_broker_main.s

# target to generate assembly for a file
examples/zcm_broker_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_broker_main.dir/build.make CMakeFiles/zcm_broker_main.dir/examples/zcm_broker_main.c.s
.PHONY : examples/zcm_broker_main.c.s

examples/zcm_bytes_pub.o: examples/zcm_bytes_pub.c.o
.PHONY : examples/zcm_bytes_pub.o

# target to build an object file
examples/zcm_bytes_pub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_bytes_pub.dir/build.make CMakeFiles/zcm_bytes_pub.dir/examples/zcm_bytes_pub.c.o
.PHONY : examples/zcm_bytes_pub.c.o

examples/zcm_bytes_pub.i: examples/zcm_bytes_pub.c.i
.PHONY : examples/zcm_bytes_pub.i

# target to preprocess a source file
examples/zcm_bytes_pub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_bytes_pub.dir/build.make CMakeFiles/zcm_bytes_pub.dir/examples/zcm_bytes_pub.c.i
.PHONY : examples/zcm_bytes_pub.c.i

examples/zcm_bytes_pub.s: examples/zcm_bytes_pub.c.s
.PHONY : examples/zcm_bytes_pub.s

# target to generate assembly for a file
examples/zcm_bytes_pub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_bytes_pub.dir/build.make CMakeFiles/zcm_bytes_pub.dir/examples/zcm_bytes_pub.c.s
.PHONY : examples/zcm_bytes_pub.c.s

examples/zcm_bytes_sub.o: examples/zcm_bytes_sub.c.o
.PHONY : examples/zcm_bytes_sub.o

# target to build an object file
examples/zcm_bytes_sub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_bytes_sub.dir/build.make CMakeFiles/zcm_bytes_sub.dir/examples/zcm_bytes_sub.c.o
.PHONY : examples/zcm_bytes_sub.c.o

examples/zcm_bytes_sub.i: examples/zcm_bytes_sub.c.i
.PHONY : examples/zcm_bytes_sub.i

# target to preprocess a source file
examples/zcm_bytes_sub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_bytes_sub.dir/build.make CMakeFiles/zcm_bytes_sub.dir/examples/zcm_bytes_sub.c.i
.PHONY : examples/zcm_bytes_sub.c.i

examples/zcm_bytes_sub.s: examples/zcm_bytes_sub.c.s
.PHONY : examples/zcm_bytes_sub.s

# target to generate assembly for a file
examples/zcm_bytes_sub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_bytes_sub.dir/build.make CMakeFiles/zcm_bytes_sub.dir/examples/zcm_bytes_sub.c.s
.PHONY : examples/zcm_bytes_sub.c.s

examples/zcm_pub.o: examples/zcm_pub.c.o
.PHONY : examples/zcm_pub.o

# target to build an object file
examples/zcm_pub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_pub.dir/build.make CMakeFiles/zcm_pub.dir/examples/zcm_pub.c.o
.PHONY : examples/zcm_pub.c.o

examples/zcm_pub.i: examples/zcm_pub.c.i
.PHONY : examples/zcm_pub.i

# target to preprocess a source file
examples/zcm_pub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_pub.dir/build.make CMakeFiles/zcm_pub.dir/examples/zcm_pub.c.i
.PHONY : examples/zcm_pub.c.i

examples/zcm_pub.s: examples/zcm_pub.c.s
.PHONY : examples/zcm_pub.s

# target to generate assembly for a file
examples/zcm_pub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_pub.dir/build.make CMakeFiles/zcm_pub.dir/examples/zcm_pub.c.s
.PHONY : examples/zcm_pub.c.s

examples/zcm_sub.o: examples/zcm_sub.c.o
.PHONY : examples/zcm_sub.o

# target to build an object file
examples/zcm_sub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_sub.dir/build.make CMakeFiles/zcm_sub.dir/examples/zcm_sub.c.o
.PHONY : examples/zcm_sub.c.o

examples/zcm_sub.i: examples/zcm_sub.c.i
.PHONY : examples/zcm_sub.i

# target to preprocess a source file
examples/zcm_sub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_sub.dir/build.make CMakeFiles/zcm_sub.dir/examples/zcm_sub.c.i
.PHONY : examples/zcm_sub.c.i

examples/zcm_sub.s: examples/zcm_sub.c.s
.PHONY : examples/zcm_sub.s

# target to generate assembly for a file
examples/zcm_sub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_sub.dir/build.make CMakeFiles/zcm_sub.dir/examples/zcm_sub.c.s
.PHONY : examples/zcm_sub.c.s

src/zcm_broker.o: src/zcm_broker.c.o
.PHONY : src/zcm_broker.o

# target to build an object file
src/zcm_broker.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_broker.c.o
.PHONY : src/zcm_broker.c.o

src/zcm_broker.i: src/zcm_broker.c.i
.PHONY : src/zcm_broker.i

# target to preprocess a source file
src/zcm_broker.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_broker.c.i
.PHONY : src/zcm_broker.c.i

src/zcm_broker.s: src/zcm_broker.c.s
.PHONY : src/zcm_broker.s

# target to generate assembly for a file
src/zcm_broker.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_broker.c.s
.PHONY : src/zcm_broker.c.s

src/zcm_core.o: src/zcm_core.c.o
.PHONY : src/zcm_core.o

# target to build an object file
src/zcm_core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_core.c.o
.PHONY : src/zcm_core.c.o

src/zcm_core.i: src/zcm_core.c.i
.PHONY : src/zcm_core.i

# target to preprocess a source file
src/zcm_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_core.c.i
.PHONY : src/zcm_core.c.i

src/zcm_core.s: src/zcm_core.c.s
.PHONY : src/zcm_core.s

# target to generate assembly for a file
src/zcm_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_core.c.s
.PHONY : src/zcm_core.c.s

src/zcm_msg.o: src/zcm_msg.c.o
.PHONY : src/zcm_msg.o

# target to build an object file
src/zcm_msg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_msg.c.o
.PHONY : src/zcm_msg.c.o

src/zcm_msg.i: src/zcm_msg.c.i
.PHONY : src/zcm_msg.i

# target to preprocess a source file
src/zcm_msg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_msg.c.i
.PHONY : src/zcm_msg.c.i

src/zcm_msg.s: src/zcm_msg.c.s
.PHONY : src/zcm_msg.s

# target to generate assembly for a file
src/zcm_msg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_msg.c.s
.PHONY : src/zcm_msg.c.s

src/zcm_node.o: src/zcm_node.c.o
.PHONY : src/zcm_node.o

# target to build an object file
src/zcm_node.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_node.c.o
.PHONY : src/zcm_node.c.o

src/zcm_node.i: src/zcm_node.c.i
.PHONY : src/zcm_node.i

# target to preprocess a source file
src/zcm_node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_node.c.i
.PHONY : src/zcm_node.c.i

src/zcm_node.s: src/zcm_node.c.s
.PHONY : src/zcm_node.s

# target to generate assembly for a file
src/zcm_node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm.dir/build.make CMakeFiles/zcm.dir/src/zcm_node.c.s
.PHONY : src/zcm_node.c.s

tests/zcm_msg_fuzz.o: tests/zcm_msg_fuzz.c.o
.PHONY : tests/zcm_msg_fuzz.o

# target to build an object file
tests/zcm_msg_fuzz.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_fuzz.dir/build.make CMakeFiles/zcm_msg_fuzz.dir/tests/zcm_msg_fuzz.c.o
.PHONY : tests/zcm_msg_fuzz.c.o

tests/zcm_msg_fuzz.i: tests/zcm_msg_fuzz.c.i
.PHONY : tests/zcm_msg_fuzz.i

# target to preprocess a source file
tests/zcm_msg_fuzz.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_fuzz.dir/build.make CMakeFiles/zcm_msg_fuzz.dir/tests/zcm_msg_fuzz.c.i
.PHONY : tests/zcm_msg_fuzz.c.i

tests/zcm_msg_fuzz.s: tests/zcm_msg_fuzz.c.s
.PHONY : tests/zcm_msg_fuzz.s

# target to generate assembly for a file
tests/zcm_msg_fuzz.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_fuzz.dir/build.make CMakeFiles/zcm_msg_fuzz.dir/tests/zcm_msg_fuzz.c.s
.PHONY : tests/zcm_msg_fuzz.c.s

tests/zcm_msg_roundtrip.o: tests/zcm_msg_roundtrip.c.o
.PHONY : tests/zcm_msg_roundtrip.o

# target to build an object file
tests/zcm_msg_roundtrip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_roundtrip.dir/build.make CMakeFiles/zcm_msg_roundtrip.dir/tests/zcm_msg_roundtrip.c.o
.PHONY : tests/zcm_msg_roundtrip.c.o

tests/zcm_msg_roundtrip.i: tests/zcm_msg_roundtrip.c.i
.PHONY : tests/zcm_msg_roundtrip.i

# target to preprocess a source file
tests/zcm_msg_roundtrip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_roundtrip.dir/build.make CMakeFiles/zcm_msg_roundtrip.dir/tests/zcm_msg_roundtrip.c.i
.PHONY : tests/zcm_msg_roundtrip.c.i

tests/zcm_msg_roundtrip.s: tests/zcm_msg_roundtrip.c.s
.PHONY : tests/zcm_msg_roundtrip.s

# target to generate assembly for a file
tests/zcm_msg_roundtrip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_roundtrip.dir/build.make CMakeFiles/zcm_msg_roundtrip.dir/tests/zcm_msg_roundtrip.c.s
.PHONY : tests/zcm_msg_roundtrip.c.s

tests/zcm_msg_vectors.o: tests/zcm_msg_vectors.c.o
.PHONY : tests/zcm_msg_vectors.o

# target to build an object file
tests/zcm_msg_vectors.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_vectors.dir/build.make CMakeFiles/zcm_msg_vectors.dir/tests/zcm_msg_vectors.c.o
.PHONY : tests/zcm_msg_vectors.c.o

tests/zcm_msg_vectors.i: tests/zcm_msg_vectors.c.i
.PHONY : tests/zcm_msg_vectors.i

# target to preprocess a source file
tests/zcm_msg_vectors.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_vectors.dir/build.make CMakeFiles/zcm_msg_vectors.dir/tests/zcm_msg_vectors.c.i
.PHONY : tests/zcm_msg_vectors.c.i

tests/zcm_msg_vectors.s: tests/zcm_msg_vectors.c.s
.PHONY : tests/zcm_msg_vectors.s

# target to generate assembly for a file
tests/zcm_msg_vectors.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_msg_vectors.dir/build.make CMakeFiles/zcm_msg_vectors.dir/tests/zcm_msg_vectors.c.s
.PHONY : tests/zcm_msg_vectors.c.s

tests/zcm_smoke.o: tests/zcm_smoke.c.o
.PHONY : tests/zcm_smoke.o

# target to build an object file
tests/zcm_smoke.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_smoke.dir/build.make CMakeFiles/zcm_smoke.dir/tests/zcm_smoke.c.o
.PHONY : tests/zcm_smoke.c.o

tests/zcm_smoke.i: tests/zcm_smoke.c.i
.PHONY : tests/zcm_smoke.i

# target to preprocess a source file
tests/zcm_smoke.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_smoke.dir/build.make CMakeFiles/zcm_smoke.dir/tests/zcm_smoke.c.i
.PHONY : tests/zcm_smoke.c.i

tests/zcm_smoke.s: tests/zcm_smoke.c.s
.PHONY : tests/zcm_smoke.s

# target to generate assembly for a file
tests/zcm_smoke.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zcm_smoke.dir/build.make CMakeFiles/zcm_smoke.dir/tests/zcm_smoke.c.s
.PHONY : tests/zcm_smoke.c.s

tools/cm-bridge/cm_bridge.o: tools/cm-bridge/cm_bridge.c.o
.PHONY : tools/cm-bridge/cm_bridge.o

# target to build an object file
tools/cm-bridge/cm_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm_bridge.dir/build.make CMakeFiles/cm_bridge.dir/tools/cm-bridge/cm_bridge.c.o
.PHONY : tools/cm-bridge/cm_bridge.c.o

tools/cm-bridge/cm_bridge.i: tools/cm-bridge/cm_bridge.c.i
.PHONY : tools/cm-bridge/cm_bridge.i

# target to preprocess a source file
tools/cm-bridge/cm_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm_bridge.dir/build.make CMakeFiles/cm_bridge.dir/tools/cm-bridge/cm_bridge.c.i
.PHONY : tools/cm-bridge/cm_bridge.c.i

tools/cm-bridge/cm_bridge.s: tools/cm-bridge/cm_bridge.c.s
.PHONY : tools/cm-bridge/cm_bridge.s

# target to generate assembly for a file
tools/cm-bridge/cm_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cm_bridge.dir/build.make CMakeFiles/cm_bridge.dir/tools/cm-bridge/cm_bridge.c.s
.PHONY : tools/cm-bridge/cm_bridge.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... cm_bridge"
	@echo "... zcm"
	@echo "... zcm_broker_ctl"
	@echo "... zcm_broker_main"
	@echo "... zcm_bytes_pub"
	@echo "... zcm_bytes_sub"
	@echo "... zcm_msg_fuzz"
	@echo "... zcm_msg_roundtrip"
	@echo "... zcm_msg_vectors"
	@echo "... zcm_pub"
	@echo "... zcm_smoke"
	@echo "... zcm_sub"
	@echo "... examples/zcm_broker_ctl.o"
	@echo "... examples/zcm_broker_ctl.i"
	@echo "... examples/zcm_broker_ctl.s"
	@echo "... examples/zcm_broker_main.o"
	@echo "... examples/zcm_broker_main.i"
	@echo "... examples/zcm_broker_main.s"
	@echo "... examples/zcm_bytes_pub.o"
	@echo "... examples/zcm_bytes_pub.i"
	@echo "... examples/zcm_bytes_pub.s"
	@echo "... examples/zcm_bytes_sub.o"
	@echo "... examples/zcm_bytes_sub.i"
	@echo "... examples/zcm_bytes_sub.s"
	@echo "... examples/zcm_pub.o"
	@echo "... examples/zcm_pub.i"
	@echo "... examples/zcm_pub.s"
	@echo "... examples/zcm_sub.o"
	@echo "... examples/zcm_sub.i"
	@echo "... examples/zcm_sub.s"
	@echo "... src/zcm_broker.o"
	@echo "... src/zcm_broker.i"
	@echo "... src/zcm_broker.s"
	@echo "... src/zcm_core.o"
	@echo "... src/zcm_core.i"
	@echo "... src/zcm_core.s"
	@echo "... src/zcm_msg.o"
	@echo "... src/zcm_msg.i"
	@echo "... src/zcm_msg.s"
	@echo "... src/zcm_node.o"
	@echo "... src/zcm_node.i"
	@echo "... src/zcm_node.s"
	@echo "... tests/zcm_msg_fuzz.o"
	@echo "... tests/zcm_msg_fuzz.i"
	@echo "... tests/zcm_msg_fuzz.s"
	@echo "... tests/zcm_msg_roundtrip.o"
	@echo "... tests/zcm_msg_roundtrip.i"
	@echo "... tests/zcm_msg_roundtrip.s"
	@echo "... tests/zcm_msg_vectors.o"
	@echo "... tests/zcm_msg_vectors.i"
	@echo "... tests/zcm_msg_vectors.s"
	@echo "... tests/zcm_smoke.o"
	@echo "... tests/zcm_smoke.i"
	@echo "... tests/zcm_smoke.s"
	@echo "... tools/cm-bridge/cm_bridge.o"
	@echo "... tools/cm-bridge/cm_bridge.i"
	@echo "... tools/cm-bridge/cm_bridge.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

